services:
    nginx:
        image: nginx:stable-alpine
        env_file:
            - .env
        environment:
            - NODE_HOST=app
        command: /bin/sh /entry.sh
        networks:
            - templrjs
        ports:
            - ${NGINX_PORT}:80
        volumes:
            - ./${CONFIG_WEB}:/etc/nginx/templates
            - ./${BIN_NGINX_ENTRY}:/entry.sh
        depends_on:
            - app
    app:
        env_file:
            - .env
            - packages/presentation/.env
        environment:
            - NODE_HOST=app
        build:
            context: .
            dockerfile: ./Dockerfile
            args:
                USERNAME: runner
                USER_UID: 1002
                USER_GID: 1002
                BIN_DEPLOY: ${BIN_DEPLOY}
                DOCKER_ENV_DIR: ${DOCKER_ENV_DIR}
                BIN_DEPLOY_REQ_SERVER: ${BIN_DEPLOY_REQ_SERVER}
                NODE_VER: ${NODE_VER}
                BUN_VER: ${BUN_VER}
                PM2_WORKER: ${PM2_WORKER}
        networks:
            - templrjs
networks:
    templrjs:
        name: templrjs
        driver: bridge
