import { z } from 'zod';

const RevealJSConfig = z.object({
    controls: z.boolean(),
    controlsTutorial: z.boolean(),
    controlsLayout: z.enum(['edges', 'bottom-right', 'bottom-left']),
    controlsBackArrows: z.enum(['faded', 'hidden', 'visible']),
    progress: z.boolean(),
    slideNumber: z.union([z.boolean(), z.enum(['h.v', 'h/v', 'c', 'c/t'])]),
    showSlideNumber: z.enum(['all', 'print', 'speaker']),
    hashOneBasedIndex: z.boolean(),
    hash: z.boolean(),
    respondToHashChanges: z.boolean(),
    history: z.boolean(),
    keyboard: z.boolean(),
    keyboardCondition: z.enum(['focused']).optional(),
    disableLayout: z.boolean(),
    overview: z.boolean(),
    center: z.boolean(),
    touch: z.boolean(),
    loop: z.boolean(),
    rtl: z.boolean(),
    shuffle: z.boolean(),
    fragments: z.boolean(),
    fragmentInURL: z.boolean(),
    embedded: z.boolean(),
    help: z.boolean(),
    pause: z.boolean(),
    showNotes: z.boolean(),
    autoAnimate: z.boolean(),
    autoPlayMedia: z.boolean().optional(),
    preloadIframes: z.boolean().optional(),
    hideCursorTime: z.number(),
    margin: z.number(),
    width: z.number(),
    height: z.number(),
    minScale: z.number(),
    maxScale: z.number(),
    pdfPageHeightOffset: z.number(),
    viewDistance: z.number(),
    mobileViewDistance: z.number(),
    autoAnimateDuration: z.number(),
    hideInactiveCursor: z.boolean(),
    mouseWheel: z.boolean(),
    previewLinks: z.boolean(),
    postMessage: z.boolean(),
    postMessageEvents: z.boolean(),
    focusBodyOnPageVisibilityChange: z.boolean(),
    pdfSeparateFragments: z.boolean(),
    autoSlideStoppable: z.boolean(),
    autoAnimateUnmatched: z.boolean(),
    autoAnimateMatcher: z.string().optional(),
    autoAnimateEasing: z.string(),
    autoAnimateStyles: z.array(z.string()),
    autoSlideMethod: z.string().optional(),
    display: z.string(),
    navigationMode: z.enum(['default', 'linear', 'grid']),
    autoSlide: z.union([z.literal(false), z.number()]),
    pdfMaxPagesPerSlide: z.number(),
    transitionSpeed: z.enum(['default', 'fast', 'slow']),
    transition: z.enum(['none', 'fade', 'slide', 'convex', 'concave', 'zoom']),
    backgroundTransition: z.enum(['none', 'fade', 'slide', 'convex', 'concave', 'zoom']),
});

export default RevealJSConfig;
