services:
    nginx:
        environment:
            NODE_HOST: dev
    dev:
        user: devu
        env_file:
            - .env
        build:
            context: .
            dockerfile: configs/docker/dev.Dockerfile
            args:
                USERNAME: devu
                USER_UID: 1001
                USER_GID: 1001
                WORK_DIR: /workspace
                BIN_DEPLOY_PREP: ${BIN_DEPLOY_PREP}
                BIN_DEPLOY_REQ: ${BIN_DEPLOY_REQ}
                SSH_AUTH_SOCK: /ssh-agent
                BUN_BIN: ${BUN_BIN_R}
                GITCONFIG_PATH: ${GITCONFIG_PATH}
        volumes:
            - ${SSH_AUTH_SOCK:-/dev/null}:/ssh-agent
            - .:/workspace
            - ${GITCONFIG_PATH:-${HOME}/.gitconfig}:/etc/gitconfig:ro
        networks:
            - templrjs
            - ollama
        expose:
            - '${NODE_PORT}'

networks:
    ollama:
        name: ollama
        driver: bridge
